# Stage 1: build image with dependencies
FROM python:3.11-slim-bookworm AS builder
WORKDIR /app
COPY requirements.txt .
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        gcc \
        libc6-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir -r requirements.txt

# Stage 2: build final image
FROM python:3.11-slim-bookworm
WORKDIR /app
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -m -u 1000 user
USER user
COPY --from=builder /usr/local /usr/local
COPY avatar_gallery.py ./avatar_gallery.py
COPY .streamlit/config.toml ./.streamlit/config.toml
COPY qr-code.png ./qr-code.png

EXPOSE 8502
CMD ["streamlit", "run", "avatar_gallery.py", \
    "--server.headless=true", \
    "--server.address=0.0.0.0", \
    "--server.enableCORS=true",  \
    "--server.port=8502", \
    "--browser.serverPort=8502"]